In [1]:
import numpy as np

In [2]:
row=np.array([1,2,3])
print("Rows : ",row)

Rows :  [1 2 3]


In [3]:
cols=np.array([[1],[2],[3]])
print("Columns : ",cols)

Columns :  [[1]
 [2]
 [3]]


# Square matrix

In [4]:
sq_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Square Matrix",sq_matrix)

Square Matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Rectangle matrix

In [14]:
rect_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Rectangular Matrix:", rect_matrix)

Rectangular Matrix: [[1 2 3]
 [4 5 6]]


# Diagonal matrix

In [10]:
dig = np.diag([1, 2, 3])
print("Diagonal Matrix: \n", dig)

Diagonal Matrix: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


# Scalar matrix

In [11]:
scalar_matrix = np.identity(3) * 5
print("Scalar Matrix:\n", scalar_matrix)

Scalar Matrix:
 [[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


# Identity Matrix

In [12]:
id_matrix = np.eye(3)
print("Identity Matrix:\n", id_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Null matrix

In [13]:
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Lower and Upper Triangular matrix

In [15]:
A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]]) 
B = np.array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])  

print("Upper Triangular Matrix:\n", A)
print("Lower Triangular Matrix:\n", B)

Upper Triangular Matrix:
 [[1 2 3]
 [0 4 5]
 [0 0 6]]
Lower Triangular Matrix:
 [[1 0 0]
 [2 3 0]
 [4 5 6]]


# Multiplication of matrices

In [16]:
A=np.array([[1,2,3],[4,5,6],[6,7,8]])
B=np.array([[3,4,5],[5,6,7],[8,9,1]])
mul=A*B
print("Multiplication : \n",mul)

Multiplication : 
 [[ 3  8 15]
 [20 30 42]
 [48 63  8]]


In [19]:
A=np.array([[1,2,3],[5,6,7]])
transpose=A.T
print("Transpose : \n",transpose)

Transpose : 
 [[1 5]
 [2 6]
 [3 7]]


# Symmetric Matrix

In [21]:
A = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 9]])
print("Matrix A:\n", A)
print("Transpose of A:\n", A.T)
print("Is Symmetric:", np.array_equal(A, A.T))


Matrix A:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Transpose of A:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Is Symmetric: True


# Skew Symmetric matrix

In [22]:
A = np.array([[ 0,  2, -1],
              [-2,  0, -4],
              [ 1,  4,  0]])
print("Matrix A:\n", A)
print("Transpose Aᵀ:\n", A.T)
print("Is Skew-Symmetric:", np.array_equal(A.T, -A))

Matrix A:
 [[ 0  2 -1]
 [-2  0 -4]
 [ 1  4  0]]
Transpose Aᵀ:
 [[ 0 -2  1]
 [ 2  0  4]
 [-1 -4  0]]
Is Skew-Symmetric: True


# Row Echelon Form (REF) & RREF

In [23]:
from sympy import Matrix
A = Matrix([[1, 2, -1], [2, 4, -2], [3, 6, -3]])
rref_matrix, pivot_cols = A.rref()
print("Original Matrix:\n", A)
print("RREF:\n", rref_matrix)
print("Pivot Columns:", pivot_cols)


Original Matrix:
 Matrix([[1, 2, -1], [2, 4, -2], [3, 6, -3]])
RREF:
 Matrix([[1, 2, -1], [0, 0, 0], [0, 0, 0]])
Pivot Columns: (0,)


# Determent of matrix

In [24]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
det=np.linalg.det(A)
print("Determent :\n",det)

Determent :
 -9.51619735392994e-16


# Cofactors of matrix

In [25]:
from sympy import Matrix
A = Matrix([[1, 2], [3, 4]])
cofactor_matrix = A.cofactor_matrix()
adjoint = A.adjugate()
print("Matrix A:\n", A)
print("Cofactor Matrix:\n", cofactor_matrix)
print("Adjoint (Adjugate):\n", adjoint)


Matrix A:
 Matrix([[1, 2], [3, 4]])
Cofactor Matrix:
 Matrix([[4, -3], [-2, 1]])
Adjoint (Adjugate):
 Matrix([[4, -2], [-3, 1]])


In [26]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 0], [0, 1]])  
print("A+B == B+A:", np.array_equal(A + B, B + A))
print("(A+B)+B == A+(B+B):", np.array_equal((A + B) + B, A + (B + B)))
print("A*(B+B) == A*B + A*B:", np.array_equal(np.dot(A, B + B), np.dot(A, B) + np.dot(A, B)))


A+B == B+A: True
(A+B)+B == A+(B+B): True
A*(B+B) == A*B + A*B: True


In [27]:
A = np.array([[1, 2, 3], [2, 4, 6], [1, 1, 1]])
rank = np.linalg.matrix_rank(A)
print("Matrix:\n", A)
print("Rank:", rank)

Matrix:
 [[1 2 3]
 [2 4 6]
 [1 1 1]]
Rank: 2


In [28]:
from numpy.linalg import solve
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 13])
X = solve(A, B)
print("Solution of AX = B is X:\n", X)

Solution of AX = B is X:
 [2.2 3.6]
